
    -- List the number of films per category.
    
use sakila;
select *
from category;

select count(fc.film_id), c.name
from category as c
join film_category as fc
on c.category_id = fc.category_id
group by c.name;

    -- Retrieve the store ID, city, and country for each store.
    
select s.store_id, c.city, co.country
from address as a
join store as s
on a.address_id = s.address_id
join city as c
on a.city_id = c.city_id
join country as co
on co.country_id = c.country_id;


    -- Calculate the total revenue generated by each store in dollars.
select s.store_id, sum(p.amount)
from payment as p
join staff as st
on p.staff_id = st.staff_id
join store as s
on st.store_id = s.store_id
group by s.store_id;

select *
from staff;
    
    -- Determine the average running time of films for each category.

select c.name, avg(f.length)
from film as f
join film_category as fc
on f.film_id = fc.film_id
join category as c
on fc.category_id = c.category_id
group by c.category_id;